# Generated by Django 4.1.7 on 2023-03-14 16:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('medecine_name', models.CharField(max_length=255)),
                ('specification', models.TextField(max_length=255)),
                ('remarks', models.TextField()),
                ('price', models.FloatField()),
                ('retail_price', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecine_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecine_Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_no', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('SELECT_STATUS', ''), ('ORDER_STATUS', 'Pending'), ('ORDER_STATUS', 'Recieved')], default='Pending', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecine_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date_out', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('reference_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecine_recieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicaltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_name', models.CharField(max_length=50)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('employ_id', models.CharField(max_length=255)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(choices=[('SELECT_GENDER', ''), ('GENDER_MALE', 'Male'), ('GENDER_FEMALE', 'Female')], max_length=255)),
                ('location', models.CharField(max_length=15)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(choices=[('SELECT_GENDER', ''), ('GENDER_MALE', 'Male'), ('GENDER_FEMALE', 'Female')], max_length=20, verbose_name='Gender')),
                ('Work_address', models.CharField(max_length=100, verbose_name='Work Address')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=255, verbose_name='About')),
            ],
        ),
    ]
