# Generated by Django 4.1.7 on 2023-03-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyPharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='medicaltype',
            name='Created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='medecine_recieved',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='medecine_recieved',
            name='medecine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.medecine'),
        ),
        migrations.AddField(
            model_name='medecine_recieved',
            name='oder_no',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.expressions.Case, to='MyPharmacy.medecine_oder'),
        ),
        migrations.AddField(
            model_name='medecine_recieved',
            name='suplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='medecine_out',
            name='done_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='medecine_out',
            name='medecine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.medecine'),
        ),
        migrations.AddField(
            model_name='medecine_oder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='medecine_oder',
            name='medecine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.medecine'),
        ),
        migrations.AddField(
            model_name='medecine_oder',
            name='suplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='medecine_category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='medecine_category',
            name='medecine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.medicaltype'),
        ),
        migrations.AddField(
            model_name='medecine',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.medecine_category'),
        ),
        migrations.AddField(
            model_name='medecine',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPharmacy.pharmacist'),
        ),
    ]
